version: 1
sequences:
- protein:
    id: H
    sequence: EVQLVESGGNLVQPGGSLRLSCAASGFTFSSYSMNWVRQAPGKGLEWVSYISSSSSTIYYADSVKGRFTISRDNAKNSLYLQMNSLRAEDTAVYYCARVAAGLKDWGQGTLVTVSS
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8BK2_0.csv
- protein:
    id: L
    sequence: EIVLTQSPGTLSLSPGERATLSCRASQSISSSYLAWYQQKPGQAPRLLIFGASSRATGIPDRFSGSGSGTGFTLTISRLEPEDFAVYYCQHYDSSLPMTFGQGTKVEIK
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8BK2_1.csv
- protein:
    id: A
    sequence: GPDSDRLQQRRVAADIGAGLADALTAPLDHKDKSLQSLTLDQSVRKNEKLKLAAQGAEKTYGNGDSLNTGKLKNDKVSRFDFIRQIEVDGQLITLESGEFQIYKQDHSAVVALQIEKINNPDKIDSLINQRSFLVSGLGGEHTAFNQLPDGKAEYHGKAFSSDDAGGKLTYTIDFAAKQGHGKIEHLKTPEQNVELAAAELKADEKSHAVILGDTRYGSEEKGTYHLALFGDRAQEIAGSATVKIGEKVHEIGIAGKQLE
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8BK2_2.csv
