version: 1
sequences:
- protein:
    id: H
    sequence: EVQLVESGGGLVQPGGSLRLSCAASGFTFNTYWMSWVRQAPGKGLEWVANIQQDGSEKDYLNSVRGRFTISRDNAKKSLYLQMNSLRAEDTAVYYCARDNPASAVAFDVWGQGAMVTVSS
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8RZ2_0.csv
- protein:
    id: L
    sequence: QSALTQPPSVSEAPRRRVTIYCSGSSSNIGNNAVSWYQQLPGKSPKLLIYFDDLVTSGVSDRFSGSKSGTSASLAISGLQSEDEADYYCAAWDDRLNGVVFGGGTKLTVL
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8RZ2_1.csv
- protein:
    id: A
    sequence: MIRIKKKLILTIIYIHLFILNRLSFENAIKKTKNQENNLTLLPIKSTEEEKDDIKNGKDIKKEIDNDKENIKTNNAKDHSTYIKSYLNTNVNDGLKYLFIPSHNSFIKKYSVFNQINDGMLLNEKNDVKNNEDYKNVDYKNVNFLQYHFKELSNYNIANSIDILQEKEGHLDFVIIPHYTFLDYYKHLSYNSIYHKSSTYGKYIAVDAFIKKINEAYDKVKSKCNDIKNDLIATIKKLEHPYDINNKNDDSYRYDISEEIDDKSEETDDETEEVEDSIQDTDSNHTPSNKKKNDLMNRTFKKMMDEYNTKKKKLIKCIKNHENDFNKICMDMKNYGTNLFEQLSCYNNNFCNTNGIRYHYDEYIHKLILSVKSKNLNKDLSDMTNILQQSELLLTNLNKKMGSYIYIDTIKFIHKEMKHIFNRIEYHTKIINDKTKIIQDKIKLNIWRTFQKDELLKRILDMSNEYSLFITSDHLRQMLYNTFYSKEKHLNNIFHHLIYVLQMKFNDVPIKMEYFQTYKKNKPLTQ
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8RZ2_2.csv
