version: 1
sequences:
- protein:
    id: H
    sequence: QVQLVESGGGVVQPGRSLRLSCAASGFTFTTYTMHWVRQAPGKGLEWVALISSDGNNKYYADSVKGRFTISRDNSKNTLYLQMSSLRAEDTAVYYCARGYYSGGDAFDVWGQGTMVTVSS
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8T9Z_0.csv
- protein:
    id: L
    sequence: DIQMTQSPSTLSASVGDRVTITCRASQTITIWLAWYQQKPGKAPKLLIYDAVSLESGVPSRFRGSGSGTDFTLTISSLQPDDFATYYCQQYNNYPYTFGQGTKLEIK
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8T9Z_1.csv
- protein:
    id: A
    sequence: LKESYLEESCSTITEGYLSVLRTGWYTNVFTLEVGDVENLTCTDGPSLIKTELDLTKSALRELKTVSADQLAREEQIENPRQSRFVLGAIALGVATAAAVTAGIAIAKTIRLESEVNAIKGALKTTNEAVSTLGNGVRVLATAVRELKEFVSKNLTSAINKNKCDIADLKMAVSFSQFNRRFLNVVRQFSDNAGITPAISLDLMTDAELARAVSYMPTSAGQIKLMLENRAMVRRKGFGILIGVYGSSVIYMVQLPIFGVIDTPCWIIKAAPSCSEKDGNYACLLREDQGWYCKNAGSTVYYPNDKDCETRGDHVFCDTAAGINVAEQSRECNINISTTNYPCKVSTGRHPISMVALSPLGALVACYKGVSCSIGSNRVGIIKQLPKGCSYITNQDADTVTIDNTVYQLSKVEGEQHVIKGRPVSSSFDPIKFPEDQFNVALDQVFESIENSQALVDQSNKILNSAEKGNTGLVPR
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8T9Z_2.csv
