version: 1
sequences:
- protein:
    id: H
    sequence: QSVEESGGRLVTPGTPLTLTCTVSGFSLSNYAMIWVRQAPGEGLEWVGTISLGGYTYYANWAKGRFTISKTSTTVDLKISSPTTEDTATYFCARARWSTDSAIYTYAFDPWGPGTLVTVSS
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8TLM_0.csv
- protein:
    id: L
    sequence: AYDMTQTPASVEVAVGGTVTIKCQASQSISSYLSWYQQKPGQRPELLIYKASTLASGVSSRFKGSGSGTQFTLTISDLEAADAATYYCQQGYTSSNIDNIFGGGTEVVVK
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8TLM_1.csv
- protein:
    id: A
    sequence: MKTIIALSYIFCLVFADYKDDDDKGSENLYFQSGSMDYTLDLSVTTVTDYYYPDIFSSPCDAELIQTNGKLLLAVFYCLLFVFSLLGNSLVILVLVVCKKLRSITDVYLLNLALSDLLFVFSFPFQTYYLLDQWVFGTVMCKVVSGFYYIGFYSSMFFITLMSVDRYLAVVHAVYALKVRTIRMGTTLCLAVWLTAIMATIPLLVFYQVASEDGVLQCYSFYNQQTLKWKIFTNFKMNILGLLIPFTIFMFCYIKILHQLKRCQNHNKTKAIRLVLIVVIASLLFWVPFNVVLFLTSLHSMHILDGCSISQQLTYATHVTEIISFTHCCVNPVIYAFVGEKFKKHLSEIFQKSCSQIFNYLGRQMPRESCEKSSSCQQHSSRSSSVDYILGNSLEVLFQGPMVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKLICTTGKLPVPWPTLVTTLGYGLQCFARYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYITADKQKNGIKANFKIRHNIEDGGVQLADHYQQNTPIGDGPVLLPDNHYLSYQSKLSKDPNEKRDHMVLLEFVTAAGITLGMDELYKGSAWSHPQFEKGGGSGGGSGGSAWSHPQFEK
    msa: /src/boltz-hackathon/boltz-hackathon-template/hackathon_data/datasets/abag_public/msa/8TLM_2.csv
